print("Enter Two Number to Perform basic arithmetic operations (addition, subtraction, multiplication, division).")
n1= int(input("First Number= "))
n2= int(input("Secend Number= "))
print(f"addition of the two number {n1} + {n2} = {n1+n2}")
print(f"subtraction of the two number {n1} - {n2} = {n1-n2}")
print(f"multiplication of the two number {n1} x {n2} = {n1*n2}")
print(f"division of the two number {n1} / {n2} = {n1/n2}")
